[package]
name = "ruststorage"
version = "0.1.0"
authors = ["Tobias Schottdorf <tobias.schottdorf@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[features]
default = ["rocksdb/static-link"]

[dependencies]
libc = "*"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"